# Generated by Django 3.1.1 on 2020-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=0)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
