# Generated by Django 3.1.1 on 2020-10-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillieJeansStart', '0002_auto_20201004_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BillieJeansStart.category'),
        ),
    ]
