# Generated by Django 3.1.1 on 2020-10-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillieJeansStart', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
