# Generated by Django 3.1.3 on 2020-11-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillieJeansStart', '0005_auto_20201112_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
